# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Inner Terrestrials
email: info@innerterrestrials.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  25 years on the road and stronger than ever, Londonâ€™s legendary Inner Terrestrials are a stomping mix of dub, punk, ska, folk and general anarchic danceability. They get audiences all over the world going crazy, from Bristol to Berlin, from Warsaw to Tokyo and beyond.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://innerterrestrials.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  innerterrestrials
twitter_username: terrestrials
instagram_username: innerterrestrials
facebook_pagename: innerterrestrials
bigcartel: innerterrestrials
bandcamp: innerterrestrials
songkick: 210500-inner-terrestrials
wikipedia: inner_terrestrials
musicbrainz: #

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
permalink: /:categories/:title/
collections:
  lyrics:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
